import { TRTB_REVIEW_HIGHLIGHTS } from "./highlights/trtbData";

function SentimentIcon({ sentiment }: { sentiment: (typeof TRTB_REVIEW_HIGHLIGHTS)[number]["sentiment"] }) {
  const color = sentiment === "positive" ? "#2A8703" : sentiment === "negative" ? "#EA1100" : "#74767C";
  return (
    <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-[16px] leading-none text-white" style={{ backgroundColor: color }}>
      {sentiment === "positive" ? "✓" : sentiment === "negative" ? "×" : "−"}
    </span>
  );
}

export default function ReviewHighlights() {
  return (
    <div className="rounded-[20px] border border-[#E3E4E5] bg-white p-4">
      <div className="flex flex-col gap-3">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-1">
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M11.1458 2.79167L12.3333 2.33333L12.7708 1.16667C12.7917 1.0625 12.8958 1 13 1C13.0833 1 13.1875 1.0625 13.2083 1.16667L13.6667 2.33333L14.8333 2.79167C14.9375 2.8125 15 2.91667 15 3C15 3.10417 14.9375 3.20833 14.8333 3.22917L13.6667 3.66667L13.2083 4.85417C13.1875 4.9375 13.0833 5 13 5C12.8958 5 12.7917 4.9375 12.7708 4.85417L12.3333 3.66667L11.1458 3.22917C11.0625 3.20833 11 3.10417 11 3C11 2.91667 11.0625 2.8125 11.1458 2.79167Z" fill="#0053E2"/>
              <path d="M1.28346 8.5288L1.8189 8.3089L2.07087 8.18325H2.10236L4.87402 6.89529L6.16535 4.09948L6.29134 3.84817L6.54331 3.31414C6.6063 3.12565 6.79528 3 6.98425 3C7.17323 3 7.3622 3.12565 7.45669 3.31414L7.70866 3.84817L7.80315 4.09948L7.83465 4.13089L9.09449 6.89529L11.8976 8.18325L12.1496 8.3089L12.685 8.56021C12.874 8.62304 13 8.81152 13 9C13 9.18848 12.874 9.37696 12.685 9.4712L12.1496 9.6911L11.8976 9.81675L9.09449 11.1047L7.80315 13.8691V13.9005L7.67717 14.1518L7.45669 14.6859C7.3622 14.8743 7.17323 15 6.98425 15C6.79528 15 6.6063 14.8743 6.54331 14.6859L6.29134 14.1518L6.16535 13.9005V13.8691L4.87402 11.1047L2.10236 9.81675H2.07087L1.8189 9.6911L1.28346 9.4712C1.09449 9.37696 1 9.18848 1 9C1 8.81152 1.09449 8.62304 1.28346 8.5288Z" fill="#0053E2"/>
            </svg>
            <span className="text-[12px] font-bold leading-[18px] text-[#2E2F32]">What customers say</span>
          </div>
          <div className="flex items-center gap-1">
            <span className="text-[12px] leading-4 text-[#74767C]">Generated by AI</span>
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M7.40039 6.99976H8.60039V11.4998H7.40039V6.99976Z" fill="#74767C"/>
              <path d="M7.99961 6.29976C8.49667 6.29976 8.89961 5.89681 8.89961 5.39976C8.89961 4.9027 8.49667 4.49976 7.99961 4.49976C7.50255 4.49976 7.09961 4.9027 7.09961 5.39976C7.09961 5.89681 7.50255 6.29976 7.99961 6.29976Z" fill="#74767C"/>
              <path d="M8 14.9998C11.866 14.9998 15 11.8657 15 7.99976C15 4.13376 11.866 0.999756 8 0.999756C4.13401 0.999756 1 4.13376 1 7.99976C1 11.8657 4.13401 14.9998 8 14.9998ZM8 13.9998C4.68629 13.9998 2 11.3135 2 7.99976C2 4.68605 4.68629 1.99976 8 1.99976C11.3137 1.99976 14 4.68605 14 7.99976C14 11.3135 11.3137 13.9998 8 13.9998Z" fill="#74767C"/>
            </svg>
          </div>
        </div>

        <div className="flex flex-wrap gap-2.5">
          {TRTB_REVIEW_HIGHLIGHTS.map(({ label, sentiment }) => (
              <div
                key={label}
                aria-label={label}
                className="flex min-h-8 items-center gap-1.5 rounded-full border border-[#E3E4E5] bg-white px-2.5 py-1 text-[12px] leading-4"
              >
                <SentimentIcon sentiment={sentiment} />
                <span className="font-bold text-[#123B82]">
                  {label}
                </span>
              </div>
          ))}
        </div>
      </div>
    </div>
  );
}
