const SPARKY_AVATAR =
  "https://cdn.builder.io/api/v1/file/assets%2F02297b1ff48d4a2f8e4d9ed415c47ecf%2Fa7b40f2aa52b4d2ba5dd1649daa60e15";

const QUESTIONS = [
  "What is the design and durability of the iPhone 16 Pro?",
  "What are the battery life improvements in the iPhone 16 Pro?",
  "How does the iPhone 16 Pro's camera system compare to previous models?",
];

function InfoCircle() {
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M7.40039 6.99976H8.60039V11.4998H7.40039V6.99976Z" fill="#74767C" />
      <path d="M7.99961 6.29976C8.49667 6.29976 8.89961 5.89681 8.89961 5.39976C8.89961 4.9027 8.49667 4.49976 7.99961 4.49976C7.50255 4.49976 7.09961 4.9027 7.09961 5.39976C7.09961 5.89681 7.50255 6.29976 7.99961 6.29976Z" fill="#74767C" />
      <path d="M8 14.9998C11.866 14.9998 15 11.8657 15 7.99976C15 4.13376 11.866 0.999756 8 0.999756C4.13401 0.999756 1 4.13376 1 7.99976C1 11.8657 4.13401 14.9998 8 14.9998ZM8 13.9998C4.68629 13.9998 2 11.3135 2 7.99976C2 4.68605 4.68629 1.99976 8 1.99976C11.3137 1.99976 14 4.68605 14 7.99976C14 11.3135 11.3137 13.9998 8 13.9998Z" fill="#74767C" />
    </svg>
  );
}

function ChevronDown() {
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M8.37683 11.3338L14 5.1915L13.2463 4.49976L8 10.2304L2.75366 4.49976L2 5.1915L7.62317 11.3338C7.71999 11.4395 7.85671 11.4998 8 11.4998C8.14329 11.4998 8.28 11.4395 8.37683 11.3338Z" fill="#2E2F32" />
    </svg>
  );
}

function ChatIcon() {
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M2.55419 12.9747L3.64307 10.727L3.21525 10.0441C2.8194 9.37479 2.58885 8.6058 2.54837 7.79584L2.54195 7.52645C2.54885 4.8368 5.01649 2.5 8.27191 2.5C11.5319 2.5 14.0019 4.84335 14.0019 7.53775C14.0019 10.2322 11.5319 12.5755 8.27191 12.5755C7.79595 12.5755 7.38231 12.5527 7 12.4955V13.505C7.39769 13.5558 7.81544 13.5755 8.27191 13.5755C11.9765 13.5755 15.0019 10.8863 15.0019 7.53775C15.0019 4.18922 11.9765 1.5 8.27191 1.5C4.56731 1.5 1.54194 4.18922 1.54194 7.53775L1.54895 7.83213C1.59562 8.80953 1.87443 9.74578 2.36135 10.5647L2.50188 10.789L1.05195 13.7819L1.02102 13.861C0.902162 14.256 1.30859 14.6363 1.70807 14.4555L5 12.965V11.8672L2.55419 12.9747Z" fill="#2E2F32" />
    </svg>
  );
}

function Divider() {
  return <div className="h-px w-full bg-[#E3E4E5]" />;
}

export default function SparkyCopilot() {
  return (
    <div className="flex flex-col gap-3 bg-white px-4 py-3">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <img
            src={SPARKY_AVATAR}
            alt="Sparky"
            className="h-[38px] w-[38px] rounded-full object-cover"
          />
          <span className="text-[16px] font-bold leading-6 text-ld-text-default">
            Find your answers
          </span>
        </div>
        <div className="flex items-center gap-1">
          <span className="text-[10px] leading-4 text-[#74767C]">Generated by AI</span>
          <InfoCircle />
        </div>
      </div>

      <Divider />

      {/* FAQ questions */}
      {QUESTIONS.map((q, i) => (
        <div key={i} className="flex flex-col gap-3">
          <button className="flex w-full items-center justify-between gap-2 text-left">
            <span className="flex-1 text-[14px] leading-5 text-ld-text-default">{q}</span>
            <ChevronDown />
          </button>
          <Divider />
        </div>
      ))}

      {/* Ask a different question */}
      <button className="flex w-full items-center justify-between rounded-lg border border-[#0053E2] bg-[#E9F1FE] px-2 py-2">
        <span className="text-[14px] leading-5 text-ld-text-default">Ask a different question</span>
        <ChatIcon />
      </button>
    </div>
  );
}
