import { useState } from "react";
import {
  Sheet,
  SheetClose,
  SheetContent,
  SheetDescription,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";
import { ChevronLeft } from "../icons";
import { TRTB_KEY_FEATURES } from "./trtbData";

const DETAIL_TABS = ["Item details", "Specifications", "Warranty", "Warnings"] as const;
type DetailTab = (typeof DETAIL_TABS)[number];

const ITEM_FEATURES = [
  ...TRTB_KEY_FEATURES,
  {
    title: "Safe-Volume Listening",
    desc: "Built-in 85 dB volume limiter helps keep listening at kid-friendly levels.",
  },
  {
    title: "Adjusts as Kids Grow",
    desc: "Smooth-sliding metal headband adjusts for kids and teens ages 6-16.",
  },
];

const ITEM_DESCRIPTION =
  "GO KID-FRIENDLY. Comfort for home or school. Style to suit any teen. JBL's on-ear Cloud Foam headphone cushions offer ultimate comfort for homework session focus without the rockstar price tag. The smooth-sliding metal adjustments and feather-light build give the long-lasting, all-day comfort kids require. Not to mention they're tested and approved for safe listening for kids with their built-in volume-limiter.";

function InfoIcon() {
  return (
    <svg aria-hidden="true" width="20" height="20" viewBox="0 0 20 20" fill="none" className="mt-0.5 shrink-0">
      <circle cx="10" cy="10" r="8.5" stroke="#74767C" strokeWidth="1.5" />
      <path d="M10 9V14" stroke="#74767C" strokeWidth="1.5" strokeLinecap="round" />
      <circle cx="10" cy="6.3" r="1" fill="#74767C" />
    </svg>
  );
}

function ItemDetailsContent() {
  return (
    <div className="flex flex-col gap-5 text-[14px] leading-5 text-[#2E2F32]">
      <section>
        <div className="mb-3 flex items-center justify-between gap-3">
          <h2 className="text-[16px] font-bold leading-6">Key item features</h2>
          <div className="flex shrink-0 items-center gap-1.5 text-[#74767C]">
            <span className="text-[12px] leading-4">Generated by AI</span>
            <InfoIcon />
          </div>
        </div>
        <ul className="flex list-disc flex-col gap-3 pl-5">
          {ITEM_FEATURES.map((feature) => (
            <li key={feature.title}>
              <span className="font-bold">{feature.title}</span>
              <span className="mt-0.5 block text-[#74767C]">{feature.desc}</span>
            </li>
          ))}
        </ul>
      </section>

      <section className="flex items-start gap-3">
        <InfoIcon />
        <p className="text-[12px] leading-[18px]">
          <span className="font-bold">We aim to show you accurate product information.</span>{" "}
          Manufacturers, suppliers and others provide what you see here, and we have not verified it. <span className="underline">See our disclaimer.</span>
        </p>
      </section>

      <section>
        <h2 className="mb-2 text-[16px] font-bold leading-6">Product description</h2>
        <p>{ITEM_DESCRIPTION}</p>
      </section>
    </div>
  );
}

const SPECIFICATIONS = [
  { label: "Color category", value: "Black" },
  { label: "Wireless technology", value: "Bluetooth" },
  { label: "Battery life", value: "36 h" },
  { label: "Compatible smart control systems", value: "Alexa, Google Assistant" },
  { label: "Features", value: "Built-in Microphone" },
  { label: "Headphone style", value: "Over-Ear" },
  { label: "Brand", value: "JBL" },
  { label: "Model name", value: "Live 770NC" },
  { label: "Wireless", value: "Y" },
];

function TabContent({ tab }: { tab: DetailTab }) {
  if (tab === "Item details") {
    return <ItemDetailsContent />;
  }

  if (tab === "Specifications") {
    return (
      <div className="overflow-hidden rounded-[16px] border border-[#E3E4E5]">
        {SPECIFICATIONS.map((spec, index) => (
          <div
            key={spec.label}
            className={`grid grid-cols-[44%_56%] text-[14px] leading-6 ${index > 0 ? "border-t border-[#E3E4E5]" : ""}`}
          >
            <div className="bg-[#F7F7F7] px-4 py-5 text-[#111111]">{spec.label}</div>
            <div className="bg-white px-4 py-5 font-bold text-[#111111]">{spec.value}</div>
          </div>
        ))}
      </div>
    );
  }

  if (tab === "Warranty") {
    return <p className="text-[14px] leading-5 text-black">Sold without manufacturer warranty.</p>;
  }

  return <p className="text-[14px] leading-5 text-black">See product packaging for safety and usage information.</p>;
}

export default function TRTBItemDetailsSheet() {
  const [activeTab, setActiveTab] = useState<DetailTab>("Item details");

  return (
    <Sheet>
      <SheetTrigger asChild>
        <button type="button" className="shrink-0 text-[#2E2F32] underline">
          View item details
        </button>
      </SheetTrigger>
      <SheetContent
        side="bottom"
        className="mx-auto flex h-[92dvh] max-h-[92dvh] w-full max-w-[440px] flex-col gap-0 rounded-t-[24px] p-0"
      >
        <SheetDescription className="sr-only">Product details and specifications</SheetDescription>
        <header className="relative flex h-[76px] shrink-0 items-center justify-center px-14">
          <SheetClose asChild>
            <button type="button" aria-label="Back" className="absolute left-4 flex h-10 w-10 items-center justify-center">
              <ChevronLeft size={24} />
            </button>
          </SheetClose>
          <SheetTitle className="text-[18px] font-bold leading-6 text-[#2E2F32]">{activeTab}</SheetTitle>
        </header>

        <nav aria-label="Item detail sections" className="flex shrink-0 overflow-x-auto border-b border-[#E3E4E5] px-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
          {DETAIL_TABS.map((tab) => (
            <button
              key={tab}
              type="button"
              onClick={() => setActiveTab(tab)}
              aria-current={activeTab === tab ? "page" : undefined}
              className={`relative flex h-12 shrink-0 items-center justify-center px-3 text-[14px] ${activeTab === tab ? "font-bold text-black after:absolute after:inset-x-0 after:bottom-0 after:h-1 after:rounded-t-full after:bg-[#0071DC]" : "text-black"}`}
            >
              {tab}
            </button>
          ))}
        </nav>

        <div className="min-h-0 flex-1 overflow-y-auto px-4 py-5">
          <TabContent tab={activeTab} />
        </div>

        <footer className="flex shrink-0 items-center justify-between border-t border-[#E3E4E5] bg-white px-4 py-4 pb-[max(16px,env(safe-area-inset-bottom))]">
          <span className="text-[20px] font-bold text-[#2E2F32]">$139.84</span>
          <SheetClose asChild>
            <button type="button" className="flex h-12 items-center justify-center rounded-full bg-[#0053E2] px-10 text-[16px] font-bold text-white">
              Add to cart
            </button>
          </SheetClose>
        </footer>
      </SheetContent>
    </Sheet>
  );
}